# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/miniai/',
                'doc_host': 'https://anubhavmaity.github.io',
                'git_url': 'https://github.com/anubhavmaity/StableDiffusion-from-foundation/',
                'lib_path': 'miniai'},
  'syms': { 'miniai.lsh': { 'miniai.lsh.FastLSH': ('locality_sensitive_hashing_lsh.html#fastlsh', 'miniai/lsh.py'),
                            'miniai.lsh.FastLSH.__init__': ('locality_sensitive_hashing_lsh.html#fastlsh.__init__', 'miniai/lsh.py'),
                            'miniai.lsh.FastLSH.hashing': ('locality_sensitive_hashing_lsh.html#fastlsh.hashing', 'miniai/lsh.py'),
                            'miniai.lsh.FastLSH.query_neigbours': ( 'locality_sensitive_hashing_lsh.html#fastlsh.query_neigbours',
                                                                    'miniai/lsh.py')}}}